# Generated by Django 4.1.7 on 2023-03-11 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_remove_thirdlevelitem_parent_delete_secondlevelitem_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BaseLevelItem',
            new_name='ContentItem',
        ),
    ]
