# Generated by Django 4.1.7 on 2023-03-11 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_rename_baselevelitem_contentitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContentItem',
            new_name='Category1',
        ),
    ]
